extends:
  - react-app
rules:
  semi: warn
  no-extra-semi: warn
  no-irregular-whitespace: warn
  no-unsafe-negation: warn
  block-scoped-var: warn
  dot-notation: warn
  no-empty-function: warn
  no-eq-null: warn
  no-floating-decimal: warn
  no-invalid-this: warn
  no-implicit-globals: warn
  no-implicit-coercion: warn
  no-warning-comments: warn
  no-useless-return: warn
  no-new: warn
  no-multi-spaces:
    - warn
    - exceptions:
        ImportDeclaration: true
  no-undef-init: warn
  no-undefined: warn
  computed-property-spacing:
    - warn
    - never
  comma-style:
    - warn
    - last
  comma-spacing:
    - warn
    - before: false
      after: true
  comma-dangle:
    - warn
    - never
  camelcase: warn
  brace-style: 
    - warn
    - stroustrup
    - allowSingleLine: true