version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://${HostingBucket}/ --recursive
      - aws s3 sync build/ s3://${HostingBucket}/
cache:
  paths:
    - 'node_modules/**/*'
