version: 0.2

phases:
  install:
    commands:
      - yarn install
  build:
    commands:
      -  yarn build
  post_build:
    commands:
      - gh-pages -d build
cache:
  paths:
    - 'node_modules/**/*'
